In [1]:
from pathlib import Path
from datetime import datetime

import numpy as np
import pandas as pd
import xarray as xr
import matplotlib.pyplot as plt
import geopandas as gpd
from shapely.geometry import Point

In [91]:
# Base File
BASE_FILE = Path.cwd () / "GloFASv5_stations_metadata_calfunction_KGE_JSD_20March2026_final_corrected.csv"
glofas5_base_info = pd.read_csv(BASE_FILE)
# glofas5_base_info=glofas5_base_info.rename(columns={"KGEmod": "JDKGE"})

# Updated Infos
UPDATE_DIR = Path("/mnt/eos_rw/projects/FLOODS-RIVER/schafti/02_GloFAS_EFAS/GloFAS/GloFASv5/Calibration/01_Results/")
UPDATE_FILE1 = UPDATE_DIR / "GloFASv5_calibration_stations/GloFASv5_CALIBRATED_stations_metadata_05March2026_calibperformaces_parameters_12May2026.csv"
UPDATE_FILE2 = UPDATE_DIR / "GloFASv5_summary_results_calibration_longrun/GloFASv5_combined_evaluation_spreadsheets_runYYY_KGEJSDcheck_19june2026_udaptedIdISRAEL-STATIONS.csv"

glofas5_update1 = pd.read_csv(UPDATE_FILE1)
glofas5_update2 = pd.read_csv(UPDATE_FILE2)

In [41]:
glofas5_update1.head()

,ID,OLD_ID,name,basin,river,provider,iso,DrainageArea_prov,DrainageArea_LDD,lat,...,LakeMultiplier,SnowMeltCoef,Kling Gupta Efficiency,Correlation,Signal ratio (s/o) (Bias),Noise ratio (s/o) (Spread),sae,NSE,JDKGE,JSD
0,4015,NaN,Shkoder,Drin-Bojana,Bojana,1049,AL,5179.0,4182.178048,42.0507,...,0.50000,4.92118,0.844268,0.860221,0.976113,0.935628,214238.0,0.736524,0.835921,0.051665
1,4006,NaN,Ura_Vajgurore,Seman,Seman,1049,AL,2073.0,2116.807680,40.7742,...,NaN,3.45397,0.730214,0.731608,0.990884,1.025820,32723.4,0.454051,0.529897,0.384983
2,4013,NaN,Shoshaj,Mat,Mat,1049,AL,646.0,672.416384,41.6076,...,NaN,3.81711,0.606051,0.697508,0.784887,0.868012,69366.7,0.458918,0.598901,0.075397
3,4016,NaN,Bahcallek,Drin-Bojana,Drin,1049,AL,14173.0,12968.997890,42.0424,...,1.19257,6.50000,0.632559,0.690988,0.857802,0.861059,482099.0,0.450095,0.622894,0.084829
4,4008,NaN,Librazhd,Shkumbin,Shkumbin,1049,AL,851.0,840.497984,41.1805,...,NaN,2.50000,0.521534,0.562900,0.816079,0.936393,65904.1,0.258014,0.519453,0.044680

In [39]:
glofas5_update2.head()

,ID,lat,lon,v4calib,modKGE_v5,corr_v5,var_v5,bias_v5,NSE_v5,modKGE_v4,...,GloFASv5_JSD,GloFASv4_JSD_CAL5years,GloFASv4_JSD,v5_JSD_ALLOBS_CHECK,v5_KGE_ALL_OBS_CHECK,v5_KGEJSD_ALL_OBS_CHECK,v4_JSD_ALLOBS_CHECK_1,v4_KGE_ALL_OBS_CHECK,v4_KGEJSD_ALL_OBS_CHECK,v4_JSD_ALLOBS_CHECK
0,4,52.025,11.875,YES,0.843919,0.846666,0.972340,0.990782,0.703046,0.831768,...,0.017636,0.067378,0.067378,0.030248,0.843919,0.841015,0.098066,0.831768,0.805272,0.098066
1,5,51.875,12.625,YES,0.827867,0.830093,0.972726,1.004154,0.667512,0.818618,...,0.008810,0.075764,0.075764,0.008371,0.827867,0.827664,0.100014,0.818618,0.792872,0.100014
2,6,53.175,11.425,NaN,0.846333,0.848354,0.977979,0.988505,0.705372,0.526871,...,0.033585,0.027996,0.027996,0.070069,0.846333,0.831112,0.063057,0.526871,0.522688,0.063057
3,9,52.625,12.325,YES,0.780649,0.791356,1.067315,0.992858,0.554080,0.747630,...,0.053597,0.043157,0.043157,0.075170,0.780649,0.768127,0.073958,0.747630,0.737016,0.073958
4,11,51.925,11.825,YES,0.846091,0.857748,1.056556,0.984068,0.702088,0.816120,...,0.017720,0.047721,0.047721,0.035453,0.846091,0.842060,0.059517,0.816120,0.806728,0.059517

In [40]:
glofas5_base_info.head()

,ID,name,basin,river,provider,iso,DrainageArea_prov,DrainageArea_LDD,lat,long,...,SourceGlo,GlofasV5,Obs_start,Obs_end,Split_date_CALstart,modKGE_v5,JSD,Function,Region,Basin
0,4,Barby,Elbe,Elbe,1004,DE,94060.00,93699.47,51.984836,11.882244,...,NRT,calibrated,01/01/1980 00:00',01/01/2000 00:00',01/01/1980 00:00',0.843939,0.030255,KGEJSD,Europe,ElbeOderEmsWeser
1,5,Wittenberg / Lutherstadt,Elbe,Elbe,1004,DE,61879.00,60938.53,51.856531,12.646309,...,NRT,calibrated,01/01/1980 00:00',01/01/2011 00:00',01/01/1991 00:00',0.834721,0.009026,KGEJSD,Europe,ElbeOderEmsWeser
2,6,Malliss OP,Elbe,Muritz-Elde,1004,DE,2879.00,3161.95,53.190627,11.345254,...,NRT,calibrated,01/01/1980 00:00',31/12/2010 00:00',31/12/1990 00:00',0.867403,0.080963,KGEJSD,Europe,ElbeOderEmsWeser
3,9,Rathenow UP,Elbe,Lower Havel,1004,DE,19288.46,18271.30,52.607446,12.321014,...,efas,calibrated,01/01/1990 00:00',19/05/2010 00:00',17/05/1990 00:00',0.787487,0.073550,KGEJSD,Europe,ElbeOderEmsWeser
4,11,Calbe Grizehne,Elbe,Saale,1004,DE,23719.00,23560.46,51.916414,11.812211,...,HIST,calibrated,01/01/1980 00:00',31/12/2019 00:00',03/05/1997 00:00',0.849686,0.039989,KGEJSD,Europe,ElbeOderEmsWeser

## New versus New 2 coordinate check

In [92]:
# Correct the lat longs in file 1
invalid_mask = (
    (glofas5_update1["lat"] < -90)  | (glofas5_update1["lat"] > 90) |
    (glofas5_update1["long"] < -180) | (glofas5_update1["long"] > 180)
)

lat_mask  = (glofas5_update1["lat"]  < -90)  | (glofas5_update1["lat"]  > 90)
long_mask = (glofas5_update1["long"] < -180) | (glofas5_update1["long"] > 180)
glofas5_update1.loc[lat_mask,  "lat"]  /= 1e5
glofas5_update1.loc[long_mask, "long"] /= 1e5
glofas5_update1[invalid_mask][["lat","long"]]

        lat    long
1471  49.00 -113.31
1508  55.00 -123.04
1517  60.00 -115.58
1552  52.98 -119.00
1641  56.00  -97.36
1728  52.00 -116.47
1762  58.00 -101.39
1939 -30.00  -70.59
1968  33.05  107.00
2013   4.00  -74.50
3133  48.05   67.00
3277  32.00   -3.75
3799  60.28  124.00
3850  52.00   85.85
3919  67.00   78.22
4341  39.48  -81.00
4372  39.36  -86.00
4478  42.19  -89.00
4582  42.00  -76.63
4820  47.00 -123.49
5055 -32.13  -55.00
5292 -10.09   32.00

## New versus Old

In [24]:
# Check IDS
diff = glofas5_update2["ID"].isin(glofas5_base_info["ID"])
missing_ids = glofas5_update2.loc[~diff, "ID"]
missing = glofas5_update2[~glofas5_update2["ID"].isin(glofas5_base_info["ID"])]
print(len(missing))

0

In [53]:
# check columns if they differ from the updates 
cols_to_check = ['name', 'basin', 'river', 'provider', 'iso', 
                 'DrainageArea_prov', 'DrainageArea_LDD', 
                 'lat', 'long', 'LISFLOOD_X', 'LISFLOOD_Y']

# Align both on ID
base   = glofas5_base_info.set_index("ID")[cols_to_check].sort_index()
update = glofas5_update1.set_index("ID")[cols_to_check].sort_index()

# Boolean mask of differences
diff_mask = base != update

# Summary: how many differences per column
print(diff_mask.sum())

# Inspect actual differences for a given column, e.g. DrainageArea_prov
changed = diff_mask.any(axis=1)
pd.concat([base[changed], update[changed]], keys=["base", "update"], axis=0).sort_index(level=1)

name                   0
basin                  0
river                  2
provider               0
iso                   26
DrainageArea_prov    471
DrainageArea_LDD       0
lat                   22
long                  22
LISFLOOD_X             0
LISFLOOD_Y             0
dtype: int64

,,name,basin,river,provider,iso,DrainageArea_prov,DrainageArea_LDD,lat,long,LISFLOOD_X,LISFLOOD_Y
,ID,,,,,,,,,,,
base,190,Deutsch Brodersdorf (Straßenbrücke),Danube,Leitha,1013,AT,NaN,2104.83,47.937903,16.477205,16.475,47.925
update,190,Deutsch Brodersdorf (Straßenbrücke),Danube,Leitha,1013,AT,NaN,2104.83,47.937903,16.477205,16.475,47.925
base,380,Borgotaro,Po,Taro,1016,IT,NaN,442.15,44.514057,9.842190,9.825,44.525
update,380,Borgotaro,Po,Taro,1016,IT,NaN,442.15,44.514057,9.842190,9.825,44.525
base,396,Bomporto,Po,Panaro,1016,IT,NaN,1151.37,44.727163,11.045084,11.075,44.725
...,...,...,...,...,...,...,...,...,...,...,...,...
update,19187,R.Ilek-village Chilik,Zhayik-Kaspyi,Ilek,1148,KZ,NaN,37383.10,51.119444,54.077778,54.075,51.125
base,19208,R.Bol.Hobda-village Kogaly,Zhayik-Kaspyi,Bol Hobda,1148,KZ,NaN,14261.10,50.871389,54.792500,54.775,50.875
update,19208,R.Bol.Hobda-village Kogaly,Zhayik-Kaspyi,Bol Hobda,1148,KZ,NaN,14261.10,50.871389,54.792500,54.775,50.875
base,19217,R.Ertis-Prigranichnyi-village Alkabek,Yertis,Ertis,1148,KZ,NaN,55619.00,48.023762,85.428117,85.425,48.025
update,19217,R.Ertis-Prigranichnyi-village Alkabek,Yertis,Ertis,1148,KZ,NaN,55619.00,48.023762,85.428117,85.425,48.025

In [52]:
# Inspect actual differences for a given column, e.g. DrainageArea_prov
changed = diff_mask["lat"]
pd.concat([base[changed], update[changed]], keys=["base", "update"], axis=0).sort_index(level=1)

,,name,basin,river,provider,iso,DrainageArea_prov,DrainageArea_LDD,JDKGE,lat,long,LISFLOOD_X,LISFLOOD_Y
,ID,,,,,,,,,,,,
base,5429,Samburg,Pur,Pur,1077,RU,95100.0,94741.300000,0.935249,67.025,7.817500e+01,78.175,67.025
update,5429,Samburg,Pur,Pur,1077,RU,95100.0,94741.300000,0.929095,6700000.000,7.822000e+01,78.175,67.025
base,6739,Tuolba At Alekseevka,Lena,Tuolba,1087,RU,14400.0,13349.082110,0.778111,60.325,1.240250e+02,124.025,60.325
update,6739,Tuolba At Alekseevka,Lena,Tuolba,1087,RU,14400.0,13349.082110,0.774581,60.280,1.240000e+07,124.025,60.325
base,14573,TAZZOUGUERT,Guir,WAD GUIR,1077,MA,2370.0,2507.280000,0.371760,32.025,-3.775000e+00,-3.775,32.025
update,14573,TAZZOUGUERT,Guir,WAD GUIR,1077,MA,2370.0,2507.280000,-0.154475,3200000.000,-3.750000e+00,-3.775,32.025
base,14740,KALUNGU (60773235),Lake Mweru,KALUNGU,1077,ZM,2106.0,2273.600000,0.700231,-10.075,3.197500e+01,31.975,-10.075
update,14740,KALUNGU (60773235),Lake Mweru,KALUNGU,1077,ZM,2106.0,2273.600000,0.684570,-10.090,3.200000e+06,31.975,-10.075
base,15037,YANGXINJIANG,Han Shui,LIANSHUI HE,1077,CN,535.0,570.500000,-0.027789,33.025,1.068750e+02,106.875,33.025
update,15037,YANGXINJIANG,Han Shui,LIANSHUI HE,1077,CN,535.0,570.500000,-0.028451,33.050,1.070000e+07,106.875,33.025
base,15093,DZEZDY,Chu,ZHEZDI,1077,KZ,1410.0,1362.400000,0.408120,48.075,6.707500e+01,67.075,48.075
update,15093,DZEZDY,Chu,ZHEZDI,1077,KZ,1410.0,1362.400000,-0.092900,48.050,6.700000e+06,67.075,48.075
base,15418,MAYMA,Culym,MAYMA,1077,RU,780.0,671.200000,0.852771,51.975,8.592500e+01,85.925,51.975
update,15418,MAYMA,Culym,MAYMA,1077,RU,780.0,671.200000,0.620696,5200000.000,8.585000e+01,85.925,51.975
base,15551,EL PROFUNDO,Magdalena,SUMAPAZ,1077,CO,957.0,1013.140000,-4.029530,3.975,-7.447500e+01,-74.475,3.975
update,15551,EL PROFUNDO,Magdalena,SUMAPAZ,1077,CO,957.0,1013.140000,-4.095830,400000.000,-7.450000e+01,-74.475,3.975
base,15625,ALGARROBAL,Elqui,ELQUI,1077,CL,5669.7,5695.170000,0.785118,-29.975,-7.057500e+01,-70.575,-29.975
update,15625,ALGARROBAL,Elqui,ELQUI,1077,CL,5669.7,5695.170000,0.780490,-3000000.000,-7.059000e+01,-70.575,-29.975
base,15694,PASO DE LAS TOSCAS,Tacuarembo,ARROYO CARAGUATA,1077,UY,1097.0,1048.641152,0.509315,-32.125,-5.497500e+01,-54.975,-32.125
update,15694,PASO DE LAS TOSCAS,Tacuarembo,ARROYO CARAGUATA,1077,UY,1097.0,1048.641152,0.468057,-32.130,-5.500000e+06,-54.975,-32.125
base,15900,NEAR PERRYVILLE. IL,Kishwaukee,KISHWAUKEE,1077,US,2846.4,2867.980000,0.670413,42.175,-8.902500e+01,-89.025,42.175
update,15900,NEAR PERRYVILLE. IL,Kishwaukee,KISHWAUKEE,1077,US,2846.4,2867.980000,0.668959,42.190,-8.900000e+06,-89.025,42.175
base,16020,NEAR EDINBURGH. IN,Driftwood,SUGAR CREEK,1077,US,1227.7,1167.160000,0.706461,39.375,-8.602500e+01,-86.025,39.375
update,16020,NEAR EDINBURGH. IN,Driftwood,SUGAR CREEK,1077,US,1227.7,1167.160000,0.703233,39.360,-8.600000e+06,-86.025,39.375
base,16040,LITTLE. WV,Middle Ohio / Little Musringum / Middle Island,MIDDLE ISLAND CREEK,1077,US,1186.2,1171.980000,0.679564,39.475,-8.097500e+01,-80.975,39.475
update,16040,LITTLE. WV,Middle Ohio / Little Musringum / Middle Island,MIDDLE ISLAND CREEK,1077,US,1186.2,1171.980000,0.675916,39.480,-8.100000e+06,-80.975,39.475
base,16188,NEAR SATSOP. WASH.,Chehalis,SATSOP,1077,US,774.4,778.890000,0.676968,47.025,-1.235250e+02,-123.525,47.025
update,16188,NEAR SATSOP. WASH.,Chehalis,SATSOP,1077,US,774.4,778.890000,0.675081,4700000.000,-1.234900e+02,-123.525,47.025
base,16262,CHEMUNG. NY,Chemung,CHEMUNG,1077,US,6490.5,6544.922112,0.731597,42.025,-7.662500e+01,-76.625,42.025
update,16262,CHEMUNG. NY,Chemung,CHEMUNG,1077,US,6490.5,6544.922112,0.728496,4200000.000,-7.663000e+01,-76.625,42.025
base,16463,RED PASS,Headwaters Fraser,Fraser,1077,CA,1700.0,1760.513536,0.801920,52.975,-1.190250e+02,-119.025,52.975
update,16463,RED PASS,Headwaters Fraser,Fraser,1077,CA,1700.0,1760.513536,0.799434,52.980,-1.190000e+07,-119.025,52.975
base,16602,NEAR ALTA / NWT BOUNDARY,Hay,WHITESAND,1077,CA,3410.0,3681.540000,0.760610,59.975,-1.155750e+02,-115.575,59.975
update,16602,NEAR ALTA / NWT BOUNDARY,Hay,WHITESAND,1077,CA,3410.0,3681.540000,0.744718,6000000.000,-1.155800e+02,-115.575,59.975
base,16616,OUTLET OF MCLEOD LAKE,Williston Lake,PACK,1077,CA,3690.0,3876.740000,0.806600,54.975,-1.230250e+02,-123.025,54.975
update,16616,OUTLET OF MCLEOD LAKE,Williston Lake,PACK,1077,CA,3690.0,3876.740000,0.796643,5500000.000,-1.230400e+02,-123.025,54.975
base,16845,WHIRLPOOL POINT,Upper North Saskatchewan / Ram,North Saskatchewan,1077,CA,1920.0,1931.457536,0.629020,52.025,-1.164750e+02,-116.475,52.025
update,16845,WHIRLPOOL POINT,Upper North Saskatchewan / Ram,North Saskatchewan,1077,CA,1920.0,1931.457536,0.622191,5200000.000,-1.164700e+02,-116.475,52.025
base,16868,INTERNATIONAL BOUNDARY,St Mary,SAINT MARY,1077,CA,1210.0,1245.497728,0.863244,48.975,-1.133250e+02,-113.325,48.975
update,16868,INTERNATIONAL BOUNDARY,St Mary,SAINT MARY,1077,CA,1210.0,1245.497728,0.858817,4900000.000,-1.133100e+02,-113.325,48.975
base,16989,NEAR THOMPSON,Lower Burntwood,ODEI,1077,CA,6130.0,6122.146304,0.830065,55.975,-9.737500e+01,-97.375,55.975
update,16989,NEAR THOMPSON,Lower Burntwood,ODEI,1077,CA,6130.0,6122.146304,0.822784,5600000.000,-9.736000e+01,-97.375,55.975
base,17030,NEAR BROCHET,Cochrane,COCHRANE,1077,CA,28400.0,29255.110000,0.798351,58.025,-1.013750e+02,-101.375,58.025
update,17030,NEAR BROCHET,Cochrane,COCHRANE,1077,CA,28400.0,29255.110000,0.797692,5800000.000,-1.013900e+02,-101.375,58.025