In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import xarray as xr
import geopandas as gpd
from shapely.geometry import Point

# Set display options
pd.set_option('display.max_columns', None)
pd.set_option('display.width', None)

In [2]:

# Load the data
glofas5_data = pd.read_csv('GloFASv5_Calibration_Results_updated.csv')
print(f"\nColumn names:\n{glofas5_data.columns.tolist()}")

Column names:
['efas', 'name', 'basin', 'river', 'provider', 'iso', 'DrainageArea_prov', 'DrainageArea_LDD', 'lat_x', 'long', 'LISFLOOD_X', 'LISFLOOD_Y', 'GlofasID', 'note', 'oldnotes', 'SourceGlo', 'GlofasV5', 'ID', 'lat_y', 'lon', 'v4calib', 'v4calib_ID', 'modKGE_v5', 'corr_v5', 'var_v5', 'bias_v5', 'NSE_v5', 'modKGE_v4', 'corr_v4', 'var_v4', 'bias_v4', 'NSE_v4', 'diff_modKGE', 'diff_corr', 'diff_NSE', 'modKGE_v5_v5CAL', 'corr_v5_v5CAL', 'var_v5_v5CAL', 'bias_v5_v5CAL', 'NSE_v5_v5CAL', 'modKGE_v4_CALyearsv5', 'corr_v4_CALyearsv5', 'var_v4_CALyearsv5', 'bias_v4_CALyearsv5', 'NSE_v4_CALyearsv5', 'diff_modKGE_CALyearsv5', 'diff_corr_CALyearsv5', 'diff_NSE_CALyearsv5', 'JSD', 'GloFASv5_JSD_v5CAL', 'GloFASv5_JSD', 'GloFASv4_JSD_CAL5years', 'GloFASv4_JSD', 'Region', 'Unnamed: 36', 'Unnamed: 37', 'status']

In [8]:
# Stations Laredar
# Germany:
# -	Forggensee (Lat 47.63°, Lon 10.70°)
# -	Sylvensteinsee (Lat 47.546°, Lon 11.571°)

# Austria/Slovenia:
# -	Mur River

# Hungary:
# -	River Tisa (Lat 48.0258°, Lon  21.3087°)

# Romania
# -	Calinesti and Suplacu de Barcau reservoirs (Tur an Barcau rivers)

# For the study project:
# -	Puppling Isar
# -	Beuerberg Isar
# -	München Isar

glofas5_data[glofas5_data["basin"]=="Danube"]["modKGE_v5"].mean()

np.float64(0.7635522983193277)

In [14]:
glofas5_data[glofas5_data["iso"].isin(["AT", "RO", "SL"]) & (glofas5_data["GlofasV5"]=="calibrated")]

,efas,name,basin,river,provider,iso,DrainageArea_prov,DrainageArea_LDD,lat_x,long,LISFLOOD_X,LISFLOOD_Y,GlofasID,note,oldnotes,SourceGlo,GlofasV5,ID,lat_y,lon,v4calib,v4calib_ID,modKGE_v5,corr_v5,var_v5,bias_v5,NSE_v5,modKGE_v4,corr_v4,var_v4,bias_v4,NSE_v4,diff_modKGE,diff_corr,diff_NSE,modKGE_v5_v5CAL,corr_v5_v5CAL,var_v5_v5CAL,bias_v5_v5CAL,NSE_v5_v5CAL,modKGE_v4_CALyearsv5,corr_v4_CALyearsv5,var_v4_CALyearsv5,bias_v4_CALyearsv5,NSE_v4_CALyearsv5,diff_modKGE_CALyearsv5,diff_corr_CALyearsv5,diff_NSE_CALyearsv5,JSD,GloFASv5_JSD_v5CAL,GloFASv5_JSD,GloFASv4_JSD_CAL5years,GloFASv4_JSD,Region,Unnamed: 36,Unnamed: 37,status
150,155.0,Fischerau / Ager,Danube,Ager,1013.0,AT,1256.10,1204.05,48.085815,13.838047,13.825,48.075,,,small oscillations and change in hydrometri ze...,NRT,calibrated,155.0,48.075,13.825,NaN,NaN,0.607176,0.746665,1.006046,0.699841,0.359832,0.405049,0.723657,1.395423,0.651801,0.225553,0.202128,0.023008,0.134279,0.607176,0.746665,1.006046,0.699841,0.359832,0.405049,0.723657,1.395423,0.651801,0.225553,0.202128,0.023008,0.134279,0.157867,0.133816,0.133816,0.315071,0.315071,Europe_Danube,NaN,NaN,NaN
151,156.0,Achleiten / Donau,Danube,Danube,1013.0,AT,76653.30,76461.18,48.582691,13.503336,13.525,48.575,,only remove data before 2010 outlier 2014,Moved to better reproduce confluence/keeping i...,NRT,calibrated,156.0,48.575,13.525,NaN,NaN,0.912329,0.915326,1.022701,1.001097,0.826043,0.879933,0.917460,1.000097,1.087197,0.770475,0.032396,-0.002135,0.055568,0.912329,0.915326,1.022701,1.001097,0.826043,0.879933,0.917460,1.000097,1.087197,0.770475,0.032396,-0.002135,0.055568,0.018037,0.008045,0.008045,0.013313,0.013313,Europe_Danube,NaN,NaN,NaN
153,158.0,Kienstock,Danube,Danube,1013.0,AT,95970.00,95824.46,48.382792,15.461220,15.525,48.375,,,,NRT,calibrated,158.0,48.375,15.525,NaN,NaN,0.891416,0.892481,1.007269,0.986681,0.785365,0.874189,0.896086,0.996254,1.070825,0.748885,0.017227,-0.003604,0.036480,0.891416,0.892481,1.007269,0.986681,0.785365,0.874189,0.896086,0.996254,1.070825,0.748885,0.017227,-0.003604,0.036480,0.017142,0.007871,0.007871,0.009737,0.009737,Europe_Danube,NaN,NaN,NaN
154,159.0,Korneuburg,Danube,Danube,1013.0,AT,101536.60,101383.68,48.329485,16.332121,16.325,48.325,,only,,NRT,calibrated,159.0,48.325,16.325,NaN,NaN,0.905307,0.906095,1.011141,0.995046,0.810876,0.889635,0.912217,1.024734,1.062152,0.781265,0.015673,-0.006121,0.029611,0.905307,0.906095,1.011141,0.995046,0.810876,0.889635,0.912217,1.024734,1.062152,0.781265,0.015673,-0.006121,0.029611,0.016326,0.006354,0.006354,0.008190,0.008190,Europe_Danube,NaN,NaN,NaN
155,160.0,Linz,Danube,Danube,1013.0,AT,79490.10,79422.03,48.306920,14.284912,14.325,48.275,,,old data/Regulated,efas,calibrated,160.0,48.275,14.325,NaN,NaN,0.858536,0.906678,1.099215,1.038204,0.758402,0.881388,0.921383,1.088091,1.011325,0.816134,-0.022852,-0.014705,-0.057731,0.858536,0.906678,1.099215,1.038204,0.758402,0.881388,0.921383,1.088091,1.011325,0.816134,-0.022852,-0.014705,-0.057731,0.035637,0.018647,0.018647,0.016334,0.016334,Europe_Danube,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2614,2736.0,STANCENI,Mures. above Tirnava,Creanga,1062.0,RO,10878.22,1484.67,46.966667,25.466667,25.225,46.975,,wrong drain flow ok,Wrong area from provider/mapped close to stati...,efas,calibrated,2736.0,46.975,25.225,NaN,NaN,0.694213,0.706954,0.912754,1.004233,0.455810,0.705610,0.709085,1.002010,0.954947,0.439737,-0.011397,-0.002131,0.016074,0.694213,0.706954,0.912754,1.004233,0.455810,0.705610,0.709085,1.002010,0.954947,0.439737,-0.011397,-0.002131,0.016074,0.051367,0.072269,0.072269,0.365368,0.365368,Europe_Danube,NaN,NaN,NaN
2615,2737.0,GLODENI,Mures. above Tirnava,Mures,1062.0,RO,10878.22,3879.45,46.650000,24.616667,24.625,46.625,,wrong drain flow ok,,efas,calibrated,2737.0,46.625,24.625,NaN,NaN,0.793720,0.796054,0.970089,0.992063,0.605990,0.689976,0.744139,0.895079,0.859851,0.539045,0.103743,0.051915,0.066945,0.793720,0.796054,0.970089,0.992063,0.605990,0.689976,0.744139,0.895079,0.859851,0.539045,0.103743,0.051915,0.066945,0.029175,0.022975,0.022975,0.196224,0.196224,Europe_Danube,NaN,NaN,NaN
2616,2738.0,LUDUS,Mures. above Tirnava,Paraul de Campie,1062.0,RO,10878.22,5818.57,46.483333,24.100000,24.125,46.475,,wrong drain flow ok,,efas,calibrated,2738.0,46.475,24.125,NaN,NaN,0.776328,0.779948,0.960574,1.007199,0.573111,0.719099,0.760876,0.866695,0.937113,0.573598,0.057229,0.019072,-0.000487,0.776328,0.779948,0.960574,1.007199,0.573111,0.719099,0.760876,0.866695,0.937113,0.573598,0.057229,0.019072,-0.000487,0.026498,0.025678,0.025678,0.151425,0.151425,Europe_Danube,NaN,NaN,NaN
2624,2746.0,OLTENITA,Danube. section Lom - Arges,Dadilovat,1062.0,RO,3498.76,675617.24,44.066667,26.066667,26.625,44.075,,flow ok,,HIST,calibrated,2746.0,44.075,26.625,NaN,NaN,0.790352,0.833282,1.126643,1.010905,0.600012,0.807840,0.832961,1.088078,1.035581,0.597626,-0.017488,0.000321,0.002385,0.790352,0.833282,1.126643,1.010905,0.600012,0.807840,0.832961,1.088078,1.035581,0.597626,-0.017488,0.000321,0.002385,0.017195,0.009656,0.009656,0.014578,0.014578,Europe_Danube,NaN,NaN,NaN
2625,2747.0,BRAILA,Danube. sector Ialomita - Siret,Danube,1062.0,RO,5699.53,708826.43,45.283333,27.983333,27.975,45.275,,flow ok,,efas,calibrated,2747.0,45.275,27.975,NaN,NaN,0.806109,0.829795,1.092316,1.010078,0.612967,0.794873,0.811063,1.076083,1.024315,0.568532,0.011236,0.018731,0.044435,0.806109,0.829795,1.092316,1.010078,0.612967,0.794873,0.811063,1.076083,1.024315,0.568532,0.011236,0.018731,0.044435,0.017040,0.013294,0.013294,0.011712,0.011712,Europe_Danube,NaN,NaN,NaN

In [30]:
glofas5_data[(glofas5_data["river"]=="Barcau") & (glofas5_data["GlofasV5"]=="calibrated")][["name","lat_x","long","modKGE_v5","NSE_v5"]]
glofas5_data[(glofas5_data["iso"]=="RO") & (glofas5_data["GlofasV5"]=="calibrated")]

,efas,name,basin,river,provider,iso,DrainageArea_prov,DrainageArea_LDD,lat_x,long,LISFLOOD_X,LISFLOOD_Y,GlofasID,note,oldnotes,SourceGlo,GlofasV5,ID,lat_y,lon,v4calib,v4calib_ID,modKGE_v5,corr_v5,var_v5,bias_v5,NSE_v5,modKGE_v4,corr_v4,var_v4,bias_v4,NSE_v4,diff_modKGE,diff_corr,diff_NSE,modKGE_v5_v5CAL,corr_v5_v5CAL,var_v5_v5CAL,bias_v5_v5CAL,NSE_v5_v5CAL,modKGE_v4_CALyearsv5,corr_v4_CALyearsv5,var_v4_CALyearsv5,bias_v4_CALyearsv5,NSE_v4_CALyearsv5,diff_modKGE_CALyearsv5,diff_corr_CALyearsv5,diff_NSE_CALyearsv5,JSD,GloFASv5_JSD_v5CAL,GloFASv5_JSD,GloFASv4_JSD_CAL5years,GloFASv4_JSD,Region,Unnamed: 36,Unnamed: 37,status
714,775.0,Bistra,Danube,Viseu,1001.0,RO,1547.00,1542.02,47.863000,24.193100,24.225,47.875,,flow ok,,NRT,calibrated,775.0,47.875,24.225,NaN,NaN,0.729332,0.735454,0.976290,0.947898,0.501096,0.354338,0.720998,1.317187,0.511707,0.191881,0.374994,0.014456,0.309215,0.729332,0.735454,0.976290,0.947898,0.501096,0.354338,0.720998,1.317187,0.511707,0.191881,0.374994,0.014456,0.309215,0.059852,0.060945,0.060945,0.308145,0.308145,Europe_Danube,NaN,NaN,NaN
716,777.0,Beclean,Danube,Somesul Mare,1001.0,RO,NaN,4356.00,47.177167,24.151194,24.125,47.175,,,,NRT,calibrated,777.0,47.175,24.125,NaN,NaN,0.784290,0.789817,0.964497,0.966928,0.602430,0.658483,0.814085,1.015756,0.713955,0.580466,0.125807,-0.024268,0.021964,0.784290,0.789817,0.964497,0.966928,0.602430,0.658483,0.814085,1.015756,0.713955,0.580466,0.125807,-0.024268,0.021964,0.036606,0.049851,0.049851,0.189130,0.189130,Europe_Danube,NaN,NaN,NaN
717,778.0,Zerind,Danube,Crisul Negru,1001.0,RO,3702.00,3849.04,46.627167,21.515611,21.525,46.625,,flow ok,,NRT,calibrated,778.0,46.625,21.525,NaN,NaN,0.799687,0.820016,0.922264,0.958913,0.667332,0.221361,0.724897,0.382332,1.386112,0.403297,0.578326,0.095119,0.264034,0.799687,0.820016,0.922264,0.958913,0.667332,0.221361,0.724897,0.382332,1.386112,0.403297,0.578326,0.095119,0.264034,0.043038,0.064210,0.064210,0.383235,0.383235,Europe_Danube,NaN,NaN,NaN
718,779.0,Chisineu Cris,Danube,Crisul Alb,1001.0,RO,NaN,3726.18,46.519528,21.509667,21.525,46.525,,,close to 673/close to 673,NRT,calibrated,779.0,46.525,21.525,NaN,NaN,0.816059,0.823430,0.973211,0.955955,0.665547,0.176264,0.719142,0.399482,1.488915,0.371154,0.639795,0.104288,0.294393,0.816059,0.823430,0.973211,0.955955,0.665547,0.176264,0.719142,0.399482,1.488915,0.371154,0.639795,0.104288,0.294393,0.042998,0.065125,0.065125,0.406787,0.406787,Europe_Danube,NaN,NaN,NaN
719,780.0,Salard,Danube,Barcau,1001.0,RO,NaN,1767.45,47.231528,22.028167,22.025,47.225,,,,NRT,calibrated,780.0,47.225,22.025,NaN,NaN,0.759857,0.774430,0.919376,0.983067,0.582892,-0.271959,0.681234,0.424434,2.088573,-0.038530,1.031816,0.093196,0.621422,0.759857,0.774430,0.919376,0.983067,0.582892,-0.271959,0.681234,0.424434,2.088573,-0.038530,1.031816,0.093196,0.621422,0.080076,0.075650,0.075650,0.403302,0.403302,Europe_Danube,NaN,NaN,NaN
721,782.0,Alba Iulia,Danube,Mures,1001.0,RO,18055.00,19416.60,46.036056,23.581361,23.575,46.025,,,,HIST,calibrated,782.0,46.025,23.575,NaN,NaN,0.752139,0.814243,0.917580,1.141903,0.588834,0.804846,0.825270,1.019315,1.084744,0.595436,-0.052707,-0.011027,-0.006601,0.834474,0.835739,1.006355,0.980593,0.675189,0.773539,0.853592,1.153896,0.921479,0.677402,0.060936,-0.017853,-0.002212,0.017249,0.013747,0.005820,0.124307,0.124307,Europe_Danube,NaN,NaN,NaN
722,783.0,Arad,Danube,Mures,1001.0,RO,27280.00,27383.58,46.159889,21.320806,21.325,46.175,,,negative values preblems with river gauge co...,HIST,calibrated,783.0,46.175,21.325,NaN,NaN,0.814448,0.845540,0.934430,1.079198,0.678872,0.820697,0.847574,0.977499,1.091703,0.657393,-0.006250,-0.002034,0.021478,0.881275,0.881722,1.004691,0.990838,0.764343,0.865844,0.882784,1.064935,0.993541,0.748513,0.015432,-0.001062,0.015830,0.008429,0.009091,0.006122,0.032181,0.032181,Europe_Danube,NaN,NaN,NaN
723,784.0,Turda,Danube,Aries,1001.0,RO,NaN,2647.09,46.566278,23.784444,23.775,46.575,,flow ok,,NRT,calibrated,784.0,46.575,23.775,NaN,NaN,0.616717,0.617104,0.998323,1.017135,0.221796,0.588935,0.630353,1.176583,0.966032,0.139630,0.027783,-0.013248,0.082166,0.616717,0.617104,0.998323,1.017135,0.221796,0.588935,0.630353,1.176583,0.966032,0.139630,0.027783,-0.013248,0.082166,0.023710,0.027659,0.027659,0.175088,0.175088,Europe_Danube,NaN,NaN,NaN
724,785.0,Mihalt,Danube,Tarnava Mare,1001.0,RO,NaN,6427.13,46.171611,23.730167,23.775,46.175,,flow ok,,HIST,calibrated,785.0,46.175,23.775,NaN,NaN,0.819693,0.820178,0.987648,0.995301,0.646157,0.384551,0.839342,1.478404,0.647729,0.573819,0.435141,-0.019164,0.072338,0.809498,0.810278,0.997303,0.982993,0.627344,0.381744,0.838328,1.477683,0.642340,0.564224,0.427754,-0.028050,0.063120,0.020035,0.016101,0.015879,0.454358,0.454358,Europe_Danube,NaN,NaN,NaN
725,786.0,Sag,Danube,Timis,1001.0,RO,4493.00,4583.55,45.646200,21.178100,21.175,45.625,,,,NRT,calibrated,786.0,45.625,21.175,NaN,NaN,0.768316,0.790431,0.901603,1.008740,0.610562,0.495797,0.735729,0.585154,1.110837,0.526614,0.272519,0.054701,0.083947,0.768316,0.790431,0.901603,1.008740,0.610562,0.495797,0.735729,0.585154,1.110837,0.526614,0.272519,0.054701,0.083947,0.026325,0.054727,0.054727,0.137405,0.137405,Europe_Danube,NaN,NaN,NaN
726,787.0,Podari,Danube,Jiu,1001.0,RO,9334.00,9237.34,44.260139,23.786750,23.825,44.275,,,,NRT,calibrated,787.0,44.275,23.825,NaN,NaN,0.760398,0.760775,0.987386,0.995362,0.529464,0.450537,0.736227,0.645888,0.672986,0.364608,0.309862,0.024549,0.164856,0.760398,0.760775,0.987386,0.995362,0.529464,0.450537,0.736227,0.645888,0.672986,0.364608,0.309862,0.024549,0.164856,0.021918,0.024974,0.024974,0.016909,0.016909,Europe_Danube,NaN,NaN,NaN
727,788.0,Bals,Danube,Oltet,1001.0,RO,NaN,2131.98,44.348333,24.098889,24.125,44.375,,,,NRT,calibrated,788.0,44.375,24.125,NaN,NaN,0.653450,0.690766,0.858789,0.932687,0.464443,0.073317,0.439368,0.288365,1.194956,0.179300,0.580133,0.251398,0.285143,0.653450,0.690766,0.858789,0.932687,0.464443,0.073317,0.439368,0.288365,1.194956,0.179300,0.580133,0.251398,0.285143,0.084413,0.082787,0.082787,0.050286,0.050286,Europe_Danube,NaN,NaN,NaN
728,789.0,Alexandria,Danube,Vedea,1001.0,RO,NaN,3338.98,43.986778,25.318806,25.325,43.975,,flow ok gap 2012,,efas,calibrated,789.0,43.975,25.325,NaN,NaN,0.636323,0.638509,0.991035,0.961213,0.308846,-1.833069,0.515355,0.139784,3.655453,-0.656061,2.469393,0.123154,0.964907,0.645530,0.650628,0.990907,0.940794,0.343530,-1.598406,0.517246,0.146140,3.406156,-0.529108,2.243936,0.133382,0.872638,0.335126,0.982374,0.983015,0.942588,0.942588,Europe_Danube,NaN,NaN,NaN
729,790.0,Calugareni,Danube,Neajlov,1001.0,RO,NaN,3280.05,44.171167,25.996917,26.025,44.175,,flow ok,,efas,calibrated,790.0,44.175,26.025,NaN,NaN,0.684656,0.689628,0.958405,1.037166,0.382302,-0.743980,0.640873,0.403207,2.598854,-0.915888,1.428636,0.048756,1.298190,0.694043,0.695873,0.972434,1.018884,0.397098,-0.644483,0.648589,0.418552,2.497582,-0.751646,1.338526,0.047285,1.148744,0.027916,0.010602,0.009558,0.809438,0.809438,Europe_Danube,NaN,NaN,NaN
730,791.0,Adancata,Danube,Prahova,1001.0,RO,NaN,2252.12,44.755833,26.460583,26.425,44.775,,flow ok,,HIST,calibrated,791.0,44.775,26.425,NaN,NaN,0.680085,0.717599,0.878617,0.911337,0.499861,0.263189,0.701373,0.782563,0.362479,-0.105396,0.416896,0.016226,0.605257,0.683674,0.725403,0.875357,0.904489,0.512377,0.261568,0.701414,0.784824,0.359822,-0.107232,0.422106,0.023989,0.619609,0.043327,0.024255,0.017862,0.380584,0.380584,Europe_Danube,NaN,NaN,NaN
731,792.0,Itcani,Danube,Suceava,1001.0,RO,NaN,2394.10,47.672778,26.234639,26.225,47.675,,flow ok,,efas,calibrated,792.0,47.675,26.225,NaN,NaN,0.718207,0.732567,0.912550,1.015472,0.498918,0.582362,0.699502,0.711417,1.029017,0.488031,0.135844,0.033065,0.010887,0.738343,0.769645,0.875927,0.997397,0.581535,0.585600,0.712264,0.702394,1.019144,0.507220,0.152743,0.057380,0.074314,0.029157,0.022977,0.024198,0.436403,0.436403,Europe_Danube,NaN,NaN,NaN
732,793.0,Vranceni,Danube,Trotus,1001.0,RO,NaN,4146.00,46.209667,26.895250,26.875,46.225,,flow ok,,efas,calibrated,793.0,46.225,26.875,NaN,NaN,0.640577,0.643800,0.983623,1.045146,0.266256,0.416977,0.654234,0.580184,0.789962,0.376862,0.223600,-0.010434,-0.110606,0.715770,0.737063,0.892290,0.992956,0.521064,0.411731,0.659561,0.589260,0.752099,0.371102,0.304039,0.077502,0.149962,0.037909,0.048507,0.045571,0.019108,0.019108,Europe_Danube,NaN,NaN,NaN
733,794.0,Botarlau,Danube,Putna,1001.0,RO,NaN,3089.21,45.632194,27.386417,27.375,45.625,,flow ok,,NRT,calibrated,794.0,45.625,27.375,NaN,NaN,0.680500,0.693544,0.912963,1.024285,0.422538,0.279499,0.542350,0.443633,1.011582,0.285364,0.401001,0.151194,0.137174,0.680500,0.693544,0.912963,1.024285,0.422538,0.279499,0.542350,0.443633,1.011582,0.285364,0.401001,0.151194,0.137174,0.053471,0.041144,0.041144,0.066561,0.066561,Europe_Danube,NaN,NaN,NaN
735,796.0,Dragesti,Danube,Siret,1001.0,RO,11899.00,11796.06,46.723639,26.945444,26.925,46.725,,flow ok,,HIST,calibrated,796.0,46.725,26.925,NaN,NaN,0.771631,0.775441,1.016029,1.038323,0.522538,0.766364,0.792717,0.926980,1.079294,0.582510,0.005267,-0.017276,-0.059971,0.747424,0.757155,0.942516,0.961056,0.550609,0.744601,0.781201,0.879616,0.946488,0.606552,0.002823,-0.024046,-0.055942,0.077673,0.081527,0.047551,0.338298,0.338298,Europe_Danube,NaN,NaN,NaN
736,797.0,Radauti,Danube,Prut,1001.0,RO,9074.00,9322.66,48.238806,26.824000,26.775,48.225,,flow ok,,efas,calibrated,797.0,48.225,26.775,NaN,NaN,0.688283,0.722186,0.860544,0.976781,0.507312,0.278085,0.534678,0.463541,0.870199,0.261515,0.410197,0.187509,0.245797,0.654489,0.742325,0.783633,0.921471,0.548656,0.242543,0.547482,0.426184,0.800743,0.244457,0.411946,0.194843,0.304199,0.051928,0.039675,0.039046,0.015344,0.015344,Europe_Danube,NaN,NaN,NaN
737,798.0,Bazias,Danube,Danube,1001.0,RO,570896.00,562121.61,44.808700,21.390100,21.375,44.775,,flow ok,,efas,calibrated,798.0,44.775,21.375,NaN,NaN,0.862159,0.865431,1.029829,1.001228,0.721518,0.830350,0.840284,1.044075,1.036458,0.639573,0.031809,0.025147,0.081945,0.881327,0.881381,0.996585,0.998968,0.763790,0.841908,0.850287,0.999622,1.050785,0.668433,0.039419,0.031093,0.095357,0.006347,0.005001,0.003596,0.005855,0.005855,Europe_Danube,NaN,NaN,NaN
738,799.0,Hoghiz,Danube,Olt,1001.0,RO,7225.00,7040.22,45.991889,25.301083,25.325,45.975,,flow ok,,efas,calibrated,799.0,45.975,25.325,NaN,NaN,0.639470,0.654695,0.898251,1.019838,0.359955,0.534849,0.674259,0.911217,0.680037,0.359764,0.104621,-0.019564,0.000191,0.639470,0.654695,0.898251,1.019838,0.359955,0.534849,0.674259,0.911217,0.680037,0.359764,0.104621,-0.019564,0.000191,0.078685,0.281545,0.281545,0.709952,0.709952,Europe_Danube,NaN,NaN,NaN
739,800.0,Gurahont,Danube,Crisul Alb,1001.0,RO,NaN,1693.45,46.277722,22.342250,22.325,46.275,,gaps before 2017 but flow ok,,efas,calibrated,800.0,46.275,22.325,NaN,NaN,0.821748,0.823768,0.973689,1.004891,0.654657,0.201088,0.550094,0.357071,1.149959,0.272849,0.620660,0.273674,0.381808,0.821748,0.823768,0.973689,1.004891,0.654657,0.201088,0.550094,0.357071,1.149959,0.272849,0.620660,0.273674,0.381808,0.025063,0.029020,0.029020,0.288630,0.288630,Europe_Danube,NaN,NaN,NaN
741,802.0,Lugoj,Danube,Timis,1001.0,RO,NaN,2762.03,45.683700,21.907300,21.925,45.675,,flow ok,,NRT,calibrated,802.0,45.675,21.925,NaN,NaN,0.742236,0.760034,0.907405,0.983128,0.559948,0.526289,0.638728,0.699675,0.939260,0.404228,0.215947,0.121306,0.155720,0.742236,0.760034,0.907405,0.983128,0.559948,0.526289,0.638728,0.699675,0.939260,0.404228,0.215947,0.121306,0.155720,0.063851,0.062755,0.062755,0.036545,0.036545,Europe_Danube,NaN,NaN,NaN
742,803.0,Tupilati,Danube,Moldova,1001.0,RO,NaN,3963.47,47.084639,26.648111,26.625,47.075,,flow ok,,efas,calibrated,803.0,47.075,26.625,NaN,NaN,0.736885,0.737503,1.003980,1.017584,0.463032,0.745905,0.750904,1.010038,0.950863,0.518808,-0.009021,-0.013401,-0.055776,0.781441,0.785833,0.956444,0.998225,0.589000,0.758088,0.766246,1.002676,0.937764,0.555077,0.023353,0.019587,0.033923,0.042360,0.025454,0.028353,0.505130,0.505130,Europe_Danube,NaN,NaN,NaN
743,804.0,Frumosu,Danube,Bistrita,1001.0,RO,NaN,2962.02,47.142472,25.861917,25.875,47.125,,flow ok,,HIST,calibrated,804.0,47.125,25.875,NaN,NaN,0.832263,0.833356,1.001798,0.980973,0.671629,0.774399,0.842300,1.058061,0.849484,0.672630,0.057864,-0.008944,-0.001001,0.848454,0.849344,0.994381,0.984588,0.704211,0.773823,0.847326,1.071413,0.849180,0.680554,0.074631,0.002018,0.023657,0.023100,0.032438,0.034294,0.042020,0.042020,Europe_Danube,NaN,NaN,NaN
744,805.0,Ceatal Izmail,Danube,Ialomița,1001.0,RO,807000.00,785749.51,45.180222,28.800000,28.775,45.225,,flow ok,,efas,calibrated,805.0,45.225,28.775,NaN,NaN,0.839236,0.849758,1.057203,0.999717,0.679178,0.820607,0.827675,1.046875,1.016996,0.626975,0.018629,0.022083,0.052203,0.839236,0.849758,1.057203,0.999717,0.679178,0.820607,0.827675,1.046875,1.016996,0.626975,0.018629,0.022083,0.052203,0.014580,0.010474,0.010474,0.005753,0.005753,Europe_Danube,NaN,NaN,NaN
746,807.0,Zimnicea,Danube,Danube,1001.0,RO,658400.00,641867.38,43.630194,25.357306,25.375,43.625,,flow ok,,HIST,calibrated,807.0,43.625,25.375,NaN,NaN,0.851950,0.863991,1.051716,1.027306,0.694996,0.855178,0.865437,1.047583,1.024536,0.702036,-0.003227,-0.001446,-0.007040,0.847776,0.868481,1.075926,1.010505,0.705695,0.856063,0.868864,1.058187,1.011639,0.713389,-0.008287,-0.000382,-0.007694,0.011494,0.007388,0.005647,0.013148,0.013148,Europe_Danube,NaN,NaN,NaN
747,808.0,Lungoci,Danube,Siret,1001.0,RO,36030.00,36463.37,45.556611,27.509972,27.525,45.575,,flow ok,,efas,calibrated,808.0,45.575,27.525,NaN,NaN,0.725581,0.727098,0.972601,0.991090,0.472518,0.731163,0.748728,0.913827,1.041353,0.518126,-0.005582,-0.021630,-0.045608,0.726490,0.727827,0.980469,0.981352,0.474536,0.737055,0.750003,0.923737,1.028727,0.521749,-0.010565,-0.022176,-0.047213,0.026825,0.029116,0.027398,0.048437,0.048437,Europe_Danube,NaN,NaN,NaN
748,809.0,Cosereni,Danube,Ialomița,1001.0,RO,6265.00,6367.91,44.696972,26.571694,26.575,44.675,,flow ok,,efas,calibrated,809.0,44.675,26.575,NaN,NaN,0.675337,0.677872,0.959516,1.001029,0.379630,0.370368,0.542283,0.580924,1.106331,0.277387,0.304968,0.135589,0.102243,0.678978,0.681241,0.963790,0.988303,0.390417,0.374136,0.540398,0.585089,1.091218,0.277435,0.304842,0.140843,0.112981,0.058977,0.043955,0.040958,0.056490,0.056490,Europe_Danube,NaN,NaN,NaN
750,811.0,Cornet,Danube,Olt,1001.0,RO,13733.00,13735.92,45.385111,24.297222,24.325,45.375,,flow ok,,efas,calibrated,811.0,45.375,24.325,NaN,NaN,0.807418,0.808742,1.011814,1.019200,0.603964,0.813079,0.826059,0.979232,1.065211,0.628434,-0.005661,-0.017317,-0.024470,0.807963,0.809308,1.019577,1.011465,0.605500,0.817381,0.827185,0.985665,1.057263,0.632703,-0.009418,-0.017877,-0.027203,0.009231,0.005318,0.004645,0.033317,0.033317,Europe_Danube,NaN,NaN,NaN
1775,1889.0,SLOBOZIA,Ialomita,Bratul Borcea,1062.0,RO,9425.00,9335.34,44.550000,27.400000,27.425,44.575,,only hist flow ok,,efas,calibrated,1889.0,44.575,27.425,NaN,NaN,0.616237,0.694627,1.148795,1.178554,0.019839,0.344386,0.644938,0.775014,1.503132,-0.076834,0.271851,0.049690,0.096673,0.616237,0.694627,1.148795,1.178554,0.019839,0.344386,0.644938,0.775014,1.503132,-0.076834,0.271851,0.049690,0.096673,0.055473,0.029907,0.029907,0.099371,0.099371,Europe_Danube,NaN,NaN,NaN
1777,1891.0,OANCEA,Prut,Prut,1062.0,RO,26800.00,26837.62,45.916667,28.116667,28.175,45.925,,only hist flow ok,,efas,calibrated,1891.0,45.925,28.175,NaN,NaN,0.550860,0.591413,1.150325,1.110390,-0.154931,0.605214,0.654142,0.834997,1.094935,0.334909,-0.054354,-0.062730,-0.489841,0.550860,0.591413,1.150325,1.110390,-0.154931,0.605214,0.654142,0.834997,1.094935,0.334909,-0.054354,-0.062730,-0.489841,0.035002,0.021118,0.021118,0.042208,0.042208,Europe_Danube,NaN,NaN,NaN
1778,1892.0,SIRET,Siret,Siret,1062.0,RO,1725.00,1656.68,47.900000,26.033333,26.075,47.975,,only hist flow ok,,efas,calibrated,1892.0,47.975,26.075,NaN,NaN,0.732268,0.732501,1.006837,1.008848,0.456296,0.665919,0.666430,0.988935,0.985225,0.349231,0.066348,0.066072,0.107064,0.732268,0.732501,1.006837,1.008848,0.456296,0.665919,0.666430,0.988935,0.985225,0.349231,0.066348,0.066072,0.107064,0.030539,0.015713,0.015713,0.656095,0.656095,Europe_Danube,NaN,NaN,NaN
1913,2031.0,Tarnava Mare - BLAJ,Danube,Tarnava Mare,1062.0,RO,3775.00,3667.20,46.170901,23.920442,23.925,46.175,,only hist flow ok,moved downstream of confluence close to 785/c...,efas,calibrated,2031.0,46.175,23.925,NaN,NaN,0.749358,0.752414,0.973699,1.028824,0.503539,0.667964,0.673831,0.957833,0.954358,0.395279,0.081394,0.078583,0.108261,0.749358,0.752414,0.973699,1.028824,0.503539,0.667964,0.673831,0.957833,0.954358,0.395279,0.081394,0.078583,0.108261,0.045568,0.036925,0.036925,0.272940,0.272940,Europe_Danube,NaN,NaN,NaN
1914,2032.0,Strei - PETRENI,Danube,Strei,1062.0,RO,1750.00,1737.66,45.800000,23.033333,22.975,45.725,,only hist flow ok,,efas,calibrated,2032.0,45.725,22.975,NaN,NaN,0.781517,0.782138,1.007618,0.985407,0.566955,0.287868,0.743990,0.703710,1.594814,-0.186324,0.493650,0.038149,0.753279,0.781517,0.782138,1.007618,0.985407,0.566955,0.287868,0.743990,0.703710,1.594814,-0.186324,0.493650,0.038149,0.753279,0.025511,0.022395,0.022395,0.172007,0.172007,Europe_Danube,NaN,NaN,NaN
2412,2532.0,NOVO SELO,Danube. section Timok - Jiu,Danube,1062.0,RO,584900.00,575195.25,44.160000,22.820000,22.825,44.125,,flow ok,,efas,calibrated,2532.0,44.125,22.825,NaN,NaN,0.784519,0.829701,1.132012,1.001730,0.595801,0.798627,0.831681,1.110102,0.990145,0.619419,-0.014108,-0.001980,-0.023619,0.784519,0.829701,1.132012,1.001730,0.595801,0.798627,0.831681,1.110102,0.990145,0.619419,-0.014108,-0.001980,-0.023619,0.023253,0.012350,0.012350,0.066603,0.066603,Europe_Danube,NaN,NaN,NaN
2414,2534.0,RUSE,Danube. section Lom - Arges,Danube,1062.0,RO,669900.00,659920.52,43.860000,25.950000,25.975,43.875,,flow ok,,HIST,calibrated,2534.0,43.875,25.975,NaN,NaN,0.801557,0.836030,1.109037,1.024581,0.604268,0.812210,0.832833,1.083075,1.020462,0.616276,-0.010652,0.003197,-0.012008,0.801557,0.836030,1.109037,1.024581,0.604268,0.812210,0.832833,1.083075,1.020462,0.616276,-0.010652,0.003197,-0.012008,0.023142,0.015457,0.015457,0.022470,0.022470,Europe_Danube,NaN,NaN,NaN
2415,2535.0,SILISTRA,Danube. section Arges - Ialom,Danube,1062.0,RO,689700.00,680260.53,44.130000,27.260000,27.275,44.125,,flow ok,,efas,calibrated,2535.0,44.125,27.275,NaN,NaN,0.779544,0.822374,1.129734,1.014795,0.569525,0.786521,0.811756,1.097727,1.024229,0.556558,-0.006977,0.010618,0.012967,0.779544,0.822374,1.129734,1.014795,0.569525,0.786521,0.811756,1.097727,1.024229,0.556558,-0.006977,0.010618,0.012967,0.022738,0.019217,0.019217,0.017930,0.017930,Europe_Danube,NaN,NaN,NaN
2614,2736.0,STANCENI,Mures. above Tirnava,Creanga,1062.0,RO,10878.22,1484.67,46.966667,25.466667,25.225,46.975,,wrong drain flow ok,Wrong area from provider/mapped close to stati...,efas,calibrated,2736.0,46.975,25.225,NaN,NaN,0.694213,0.706954,0.912754,1.004233,0.455810,0.705610,0.709085,1.002010,0.954947,0.439737,-0.011397,-0.002131,0.016074,0.694213,0.706954,0.912754,1.004233,0.455810,0.705610,0.709085,1.002010,0.954947,0.439737,-0.011397,-0.002131,0.016074,0.051367,0.072269,0.072269,0.365368,0.365368,Europe_Danube,NaN,NaN,NaN
2615,2737.0,GLODENI,Mures. above Tirnava,Mures,1062.0,RO,10878.22,3879.45,46.650000,24.616667,24.625,46.625,,wrong drain flow ok,,efas,calibrated,2737.0,46.625,24.625,NaN,NaN,0.793720,0.796054,0.970089,0.992063,0.605990,0.689976,0.744139,0.895079,0.859851,0.539045,0.103743,0.051915,0.066945,0.793720,0.796054,0.970089,0.992063,0.605990,0.689976,0.744139,0.895079,0.859851,0.539045,0.103743,0.051915,0.066945,0.029175,0.022975,0.022975,0.196224,0.196224,Europe_Danube,NaN,NaN,NaN